python/Django/MyWeb/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('lang/', views.lang, name='lang'),
    path('linux/', views.linux, name='linux'),
]

python/Django/MyWeb/myweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('yiqin/', include('yiqin.urls')),
]

python/Django/MyWeb/yiqin/urls.py
from django.urls import path
from . import views

app_name = 'yiqin'

urlpatterns = [
    path('', views.index, name = 'index'),        
    path('echarts/test<int:num>/', views.test_echarts, name='echarts_test'),
    path('api/chinadayaddlist/', views.get_china_day_add_list, name='chinadayaddlist'),
]

python/Django/MyWeb/blog/models.py
from django.db import models

# Create your models here.

python/Django/MyWeb/yiqin/models.py
from django.db import models

class ChinaDayList(models.Model):
    confirm = models.IntegerField()
    suspect = models.IntegerField()
    dead = models.IntegerField()
    heal = models.IntegerField()
    nowConfirm = models.IntegerField()
    nowSevere = models.IntegerField()
    deadRate = models.CharField(max_length=20)
    healRate = models.CharField(max_length=20)
    date = models.CharField(max_length=20)

    def __str__(self):
        return self.date

class ChinaDayAddList(models.Model):
    confirm = models.IntegerField()
    suspect = models.IntegerField()
    dead = models.IntegerField()
    heal = models.IntegerField()
    deadRate = models.CharField(max_length=20)
    healRate = models.CharField(max_length=20)
    date = models.CharField(max_length=20)

    def __str__(self):
        return self.date

class DailyNewAddHistory(models.Model):
    date = models.CharField(max_length=20)
    hubei = models.IntegerField()
    country = models.IntegerField()
    notHubei = models.IntegerField()

    def __str__(self):
        return self.date

class DailyDeadRateHistory(models.Model):
    date = models.CharField(max_length=20)
    hubeiRate = models.CharField(max_length=20)
    notHubeiRate = models.CharField(max_length=20)
    countryRate = models.CharField(max_length=20)

    def __str__(self):
        return self.date

class DailyHealRateHistory(models.Model):
    date = models.CharField(max_length=20)
    hubeiRate = models.CharField(max_length=20)
    notHubeiRate = models.CharField(max_length=20)
    countryRate = models.CharField(max_length=20)

    def __str__(self):
        return self.date

class AreaTree(models.Model):
    name = models.CharField(max_length=20)
    date = models.CharField(max_length=20)
    confirm = models.IntegerField()
    totalConfirm = models.IntegerField()
    totalSuspect = models.IntegerField()
    totalDead = models.IntegerField()
    totalHeal = models.IntegerField()
    deadRate = models.CharField(max_length=20)
    healRate = models.CharField(max_length=20)
    parent = models.CharField(max_length=20, default='')
    type = models.CharField(max_length=10, default='')

    def __str__(self):
        return self.name

class ChinaAdd(models.Model):
    confirm = models.IntegerField()
    heal = models.IntegerField()
    suspect = models.IntegerField()
    dead = models.IntegerField()
    nowSevere = models.IntegerField()
    nowConfirm = models.IntegerField()
    type = models.CharField(max_length=10)
    date = models.CharField(max_length=10)

    def __str__(self):
        return self.date

class DailyHistory(models.Model):
    heal = models.IntegerField()
    dead = models.IntegerField()
    nowConfirm = models.IntegerField()
    healRate = models.CharField(max_length=10)
    deadRate = models.CharField(max_length=10)
    type = models.CharField(max_length=10)
    date = models.CharField(max_length=10)

    def __str__(self):
        return self.date

class ArticleList(models.Model):
    title = models.CharField(max_length=50)
    desc = models.TextField()
    url = models.URLField()
    media = models.CharField(max_length=50)
    cmsId = models.CharField(max_length=50)
    source = models.CharField(max_length=20)
    publish_time = models.CharField(max_length=20)
    can_use = models.IntegerField()

    def __str__(self):
        return self.title

class WuhanDayList(models.Model):
    confirmAdd = models.IntegerField()
    date = models.CharField(max_length=10)
    type = models.CharField(max_length=20)

    def __str__(self):
        return self.type

python/Django/MyWeb/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
def index(request):
    return render(request, 'blog/index.html')

def lang(request):
    return HttpResponse('lang page')

def linux(request):
    return HttpResponse('linux page')

python/Django/MyWeb/yiqin/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import ChinaDayAddList
import json

# Create your views here.

def index(request):
    return render(request, 'yiqin/index.html')

def test_echarts(request, num):
    return render(request, 'yiqin/echarts/test{}.html'.format(num))

def get_china_day_add_list(request):
    sql_data = ChinaDayAddList.objects.values().order_by('date')
    res = {
        'msg': 'ok',
        'status': 200,
        'count': ChinaDayAddList.objects.count(),
        'data': {
            'titles': [],
            'data': [],
            'date': []
        }
     } 


    data_obj = {}
    data_map = {
        'confirm': '确诊',
        'suspect': '疑似', 
        'dead': '死亡', 
        'heal': '出院', 
        'deadRate': '死亡率', 
        'healRate': '治愈率'
    }

    for item in sql_data:
        for key, val in item.items():
            if key in {'id' }:
                continue
            if data_obj.get(key):
                if isinstance(val, str):
                    data_obj[key].append(float(val))
                else:
                    data_obj[key].append(val)
            else:
                if isinstance(val, str):
                    data_obj[key] = [float(val)]
                else:
                    data_obj[key] = [val]

    for key,val in data_obj.items():
        struct = {
            'name': '',
            'type': 'line',
        }
        struct['data'] = val
        if key == 'date':
            res['data']['date'] = val
        else:
            struct['name'] = data_map[key]
            res['data']['titles'].append(data_map[key])
            res['data']['data'].append(struct)


    return HttpResponse(json.dumps(res))

python/Django/MyWeb/blog/templates/blog/base.html
<!DOCTYPE html>
<html>
	<head>
        <meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<title>{% block title %}{% endblock %}</title>
		{% load static %}
		<link rel="stylesheet" href="{% static 'lib/layui/css/layui.css' %}">
	</head>
	<body>
		<script src="{% static 'lib/layui/layui.js' %}"></script>
		{% include 'blog/nav.html' %}
		<div class="layui-container">
			{% block content %}{% endblock %}
			{% block footer %}{% endblock %}
		</div>
		{% include 'blog/footer.html' %}
		<script>
		layui.config({
			dir: "{% static 'lib/layui/' %}",
			debug: true,
//			version: true,
			base: "{% static 'blog/js/' %}"
		}).extend({
		});
		layui.use(['form', 'element', 'layer'], function(){
			
		});
		</script>
	</body>
</html>

python/Django/MyWeb/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}wmsj100博客{% endblock %}

{% block content %}
<h1>This is index page</h1>
{% endblock %}

python/Django/MyWeb/blog/templates/blog/nav.html
<ul class="layui-nav">
	<li class="layui-nav-item"><a href="{% url 'blog:index' %}">首页</a></li>
	<li class="layui-nav-item"><a href="{% url 'blog:linux' %}">Linux</a></li>
	<li class="layui-nav-item"><a href="{% url 'blog:lang' %}">编程语言</a></li>
</ul>

python/Django/MyWeb/yiqin/templates/yiqin/base.html
<!DOCTYPE html>
<html>
	<head>
        <meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<title>{% block title %}{% endblock %}</title>
		{% load static %}
		<link rel="stylesheet" href="{% static 'lib/layui/css/layui.css' %}">
	</head>
	<body>
		<script src="{% static 'lib/layui/layui.js' %}"></script>
		{% include 'yiqin/nav.html' %}
		<div class="layui-container">
			{% block content %}{% endblock %}
			{% block footer %}{% endblock %}
		</div>
		{% include 'yiqin/footer.html' %}
		<script>
		layui.config({
			dir: "{% static 'lib/layui/' %}",
			debug: true,
			base: "{% static 'yiqin/js/' %}",
		}).extend({
		});
		</script>
		<script src="{% static 'yiqin/js/index.js' %}"></script>
	</body>
</html>

python/Django/MyWeb/yiqin/templates/yiqin/echarts/test1.html
{% extends 'yiqin/base.html' %}

{% block content %}
{% load static %}
<script src="{% static 'lib/echarts/echarts.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'yiqin/css/echarts/test1.css' %}">
<h1>echarts test</h1>
<div class="layui-row layui-col-space10">
	<div class="layui-col-md12">
		<div id="yiqin"></div>
	</div>
	<div class="layui-col-md7">
		<div id="main"></div>
	</div>
	<div class="layui-col-md5">
		<div id="test1"></div>
	</div>
</div>
<script src="{% static 'yiqin/js/echarts/test1.js' %}"></script>
{% endblock %}

python/Django/MyWeb/yiqin/templates/yiqin/index.html
{% extends 'yiqin/base.html' %}

{% block title %}wmsj100博客{% endblock %}

{% block content %}
<h1>This is index page</h1>
{% endblock %}

python/Django/MyWeb/yiqin/templates/yiqin/nav.html
<ul class="layui-nav">
	<li class="layui-nav-item"><a href="{% url 'yiqin:index' %}">首页</a></li>
	<li class="layui-nav-item"><a href="{% url 'yiqin:index' %}">Linux</a></li>
	<li class="layui-nav-item"><a href="{% url 'yiqin:index' %}">编程语言</a></li>
</ul>